quarkus.http.port=${HTTP_PORT:8080}
quarkus.oidc.client-id=${OIDC_CLIENT_ID:dev}
quarkus.oidc.credentials.secret=${OIDC_CLIENT_SECRET:dev}
quarkus.oidc.auth-server-url=${OIDC_AUTH_SERVER_URL:http://localhost/oidc}
quarkus.oidc.application-type=web-app

%dev.quarkus.oidc.enabled=false
%test.quarkus.oidc.enabled=false

%dev.acofitec.security.mock.enabled=true
%test.acofitec.security.mock.enabled=true
%dev.acofitec.security.mock.username=developer
%dev.acofitec.security.mock.roles=admin,user
%dev.acofitec.security.mock.email=developer@acofitec.local
%dev.acofitec.security.mock.subject=00000000-0000-0000-0000-000000000001
%test.acofitec.security.mock.username=tester
%test.acofitec.security.mock.roles=user
