quarkus.http.port=${HTTP_PORT:8080}
quarkus.oidc.client-id=${OIDC_CLIENT_ID:dev}
quarkus.oidc.credentials.secret=${OIDC_CLIENT_SECRET:dev}
quarkus.oidc.auth-server-url=${OIDC_AUTH_SERVER_URL:http://localhost/oidc}
quarkus.oidc.application-type=web-app
