name: PR CI (Build, Native, SBOM/Scan)

on:
  pull_request:
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Build & test
        run: ./mvnw -B -ntp verify

      - name: Package application
        run: ./mvnw -B -ntp -DskipTests package
